# Template of ini file for one 1.5Mh module
# Any field that is not desired to be configured can be removed

[GENERAL CONFIGURATIONS]
threshold0=30
threshold1=100
gain=0
equalization_folder=11
mfb 2 (C) sensor bias low=300.00
mfb 2 (C) sensor bias high=300.00
mfb 2 (C) vdda_marga low=0.4

[CHIP 1]
discl=68
gnd=130
fbk=170
cas=170
shaper=125
threshold0=78
threshold1=511
extbgin=0.637

[CHIP 2]
discl=68
gnd=130
fbk=170
cas=170
shaper=125
threshold0=77
threshold1=511
extbgin=0.9

[CHIP 3]
discl=68
gnd=129
fbk=170
cas=168
shaper=125
threshold0=77
threshold1=511
extbgin=0.637

[CHIP 4]
discl=68
gnd=133
fbk=170
cas=170
shaper=125
threshold0=77
threshold1=511
extbgin=0.637

[CHIP 5]
discl=68
gnd=130
fbk=170
cas=170
shaper=125
threshold0=77
threshold1=511
extbgin=0.637

[CHIP 6]
discl=68
gnd=137
fbk=170
cas=170
shaper=125
threshold0=77
threshold1=511
extbgin=0.637
