# Template of ini file for RAD 400k
# Any field that is not desired to be configured can be removed

[paths]
MODULE 1=/home/lumentum/pimega-pss/init.templates/rad1_5M-mod1.ini
MODULE 2=/home/lumentum/pimega-pss/init.templates/rad1_5M-mod2.ini
MODULE 3=/home/lumentum/pimega-pss/init.templates/rad1_5M-mod3.ini
MODULE 4=/home/lumentum/pimega-pss/init.templates/rad1_5M-mod4.ini

# Coefficients for Energy Calibration equation
# Target Equation ------>>>   Th = E * a + b
# Examples
# High gain: Th = 5.291 * E + 3.001
# Super high gain: Th = 9.354 * E + 3.607
[CALIBRATION]
shgm_a=4.511
shgm_b=27.592
#hgm_a=5.291
#hgm_b=3.001
#lgm_a=6.148
#lgm_b=3.987
#slgm_a=2.456
#slgm_b=1.345
