# Template of ini file for one 1.5Mh module
# Any field that is not desired to be configured can be removed

[GENERAL CONFIGURATIONS]
threshold0=30
threshold1=100
gain=0
equalization_folder= 7
mfb 2 (C) sensor bias low=300.00
mfb 2 (C) sensor bias high=300.00
mfb 2 (C) vdda_marga low=0.4

[CHIP 1]
discl=68
gnd=142
fbk=196
cas=185
shaper=125
threshold0=78
threshold1=511
extbgin=0.637

[CHIP 2]
discl=68
gnd=141
fbk=195
cas=184
shaper=125
threshold0=77
threshold1=511
extbgin=0.637

[CHIP 3]
discl=68
gnd=134
fbk=189
cas=170
shaper=125
threshold0=77
threshold1=511
extbgin=0.637

[CHIP 4]
discl=68
gnd=133
fbk=177
cas=171
shaper=125
threshold0=77
threshold1=511
extbgin=0.637

[CHIP 5]
discl=68
gnd=127
fbk=182
cas=173
shaper=125
threshold0=77
threshold1=511
extbgin=0.637

[CHIP 6]
discl=68
gnd=131
fbk=187
cas=172
shaper=125
threshold0=77
threshold1=511
extbgin=0.637
